### PR TITLE
Add base rules to main config

### PR DESCRIPTION
**Pull request by pzuraq**
cc @twokul

### CODE REVIEW

**Comment by twokul** [comment]
based on our conversation offline, I thought we would keep the rules in one repo but split between 2 configs: one for Javascript-only and the other one would be Ember-specific.

**Comment by pzuraq** [comment]
The base config is javascript specific though, it just configures eslint. No Ember specific rules, just Javascript things

**Comment by pzuraq** [comment]
We can also copy those settings to the main config, but I think we should for instance enforce semis everywhere we write JS

**Comment by twokul** [comment]
@pzuraq hm. feels weird to import JS rules from Ember-specific eslint set of rules. I think this might be a breaking change, [semi](https://github.com/ember-best-practices/eslint-plugin-ember-best-practices/blob/master/config/base.js#L41)

**Comment by pzuraq** [comment]
Yeah that's a fair point. It would be a breaking change, but our styleguide was always to have semicolons: https://github.com/Addepar/styleguides/blob/master/frontend/javascript.md

They accidentally got removed when we removed ember-suave, which was including a similar base set of rules: https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/config/base.js#L41

My goal here is to bring all these rules back to both the main JS config and the new Ember config. I agree with the majority of the settings for the Ember base config, so we can either copy-paste them into the main config or include them, I'm open here.

**Pull request merged**
